### ISSUE TITLE
Raise value error in Merging dataset of files with different variables using (ds.merge())

### ISSUE THREAD

**Issue by HARSHBARDHANK94** [pmlmodelling/nctoolkit#10]
import nctoolkit as nc
files=["AOD.nc","CER.nc"]
ds = nc.open_data(files)
ds.merge()

[OUT]: ds.merge()
Traceback (most recent call last):

  File "C:\Users\HARSHB~1\AppData\Local\Temp/ipykernel_1256/1994133908.py", line 1, in <module>
    ds.merge()

  File "C:\Users\HARSHBARDHAN\anaconda3\lib\site-packages\nctoolkit\mergers.py", line 76, in merge
    ntime = int(cdo_result.split("\\")[0])

ValueError: invalid literal for int() with base 10: "'"

**Comment by HARSHBARDHANK94** [comment]
Actually I got initial warning with importing nctoolkit:

>import nctoolkit as nc
Please install CDO version 1.9.3 or above: https://code.mpimet.mpg.de/projects/cdo/ or https://anaconda.org/conda-forge/cdo

**Comment by r4ecology** [comment]
You will need to install CDO, as instructed by the warning.

**Comment by HARSHBARDHANK94** [comment]
I am installing it via anaconda prompt: checked with all.....
conda install -c conda-forge cdo
conda install -c conda-forge/label/cf202003 cdo
conda install -c conda-forge/label/dev cdo
conda install -c conda-forge/label/gcc7 cdo
conda install -c conda-forge/label/broken cdo
conda install -c conda-forge/label/cf201901 cdo

**Comment by r4ecology** [comment]
Unfortunately, nctoolkit will not work with Windows because CDO will not

**Comment by HARSHBARDHANK94** [comment]
OK, thanks for your remark.

**Comment by r4ecology** [comment]
It should work on Windows Subsystem for Linux, if you are unable to access Linux or OSX directly
