### ISSUE TITLE
Issues in Merge since update to 0.3.9

### ISSUE THREAD

**Issue by fatolahzadeh** [pmlmodelling/nctoolkit#13]
Updated from 0.3.7 to 0.3.9 and the new `merge(join='time')` has some issues when merging over time:

`cdo(1) selname: Process startedcdo(2) selname: Process startedcdo    mergetime (Abort): Outputfile batch.nc already exists!terminate called recursivelyterminate called without an active exceptionAborted (core dumped)  During handling of the above exception, another exception occurred.`

Depending on the number of files merged, the error is repeated as `Process startedcdo(3) ... `
Got the above error when merging two files that worked without issues using old `merge_time()` method.

**Comment by r4ecology** [comment]
Can you provide the code that produced the error so I can look into it?

**Comment by fatolahzadeh** [comment]
```
nc.deep_clean()
master_ds = nc.open_data("{0}/fetch/*.nc".format(data_folder))
master_ds.merge(join='time')
master_ds.tmean(["year", "month", "day"])
master_ds.to_nc("batch.nc", overwrite=True)
```

**Comment by fatolahzadeh** [comment]
BTW there are more issues. For instance, the simple code below parsing only one NetCDF file containing the variables ['rsn', 'sd', 'sde', 'sf', 'snowc', 'ssrd', 'strd', 'swvl1', 't2m', 'tp', 'u10', 'v10'] :

```
ds = nc.open_data("data/*.nc")
print(ds.variables)
ds.drop(['tp', 'sf'])
print(ds.variables)
```

Will result in:
```
['rsn', 'sd', 'sde', 'sf', 'snowc', 'ssrd', 'strd', 'swvl1', 't2m', 'tp', 'u10', 'v10'] 
['rsn', 'sd', 'sde', 'sf', 'snowc', 'ssrd', 'strd', 'swvl1', 't2m', 'tp', 'u10', 'v10'] 
```

**Comment by fatolahzadeh** [comment]
Sorry for the multiple posts, I think there are lots of unclarities regarding how the methods operate, and how they handle the precedence and "inplace". I'll try to explain through some examples:

I have several nc files (each file represent a year) that contain temperature and precipitation in hourly format, and I want to calculate monthly averages for the temperature, and the total monthly precipitation. So I have to apply `tmean` on temperature and `tsum` on precipitation, but it can't be done by default using nctoolkit library. So I `copy()` the original dataset in a new dataset, drop the temperature channel in one dataset, and select the precipitation channel on the other, and then use `tmean` and `tsum' and then merge them into one dataset and save in a new nc file...

In the first step, If I apply `merge(join='time')` and then attempt to `copy()`, it will throw:
`Exception has occurred: ValueError Attempting to overwrite file`

But if I use `copy()` and then apply `merge(join='time')` it works.

In the next step, if I apply `drop()` and select(variables = [...]), they won't affect the datasets. the `variable` attributes still point to the original variables in the files unless another copy is made from them, and then the drop() is shown to be applied to both instances before and after copying, which doens't make sense.

**Comment by r4ecology** [comment]
I am not really sure what you are asking. Have you read the website? [https://nctoolkit.readthedocs.io/en/latest/index.html](https://nctoolkit.readthedocs.io/en/latest/index.html). These issues appear to be explained there. If anything is unclear on the website, let me know and I will happily improve it.

**Comment by r4ecology** [comment]
In regards to the original issue, the processing chain is trying to overwrite an existing file, but it is unable to do so. I need to modify the source code so that it will handle this case properly. nctoolkit generates a call to CDO, but in the case of merging operations CDO cannot overwrite files that exist. So I will need to modify the `to_nc` method. In the meantime, the following should resolve your problem:

    nc.deep_clean()
    master_ds = nc.open_data("{0}/fetch/*.nc".format(data_folder))
    master_ds.merge(join='time')
    master_ds.tmean(["year", "month", "day"])
    master_ds.run()
    master_ds.to_nc("batch.nc", overwrite=True)

**Comment by r4ecology** [comment]
I've just modified `to_nc` so that it will properly overwrite pre-existing files when using merging/ensemble commands: [https://github.com/pmlmodelling/nctoolkit/commit/7bfe35fe9fe5396ee0c9a4b9eb9c378d11db5481](url).

This should close the issue.

**Comment by fatolahzadeh** [comment]
Thanks for solving the overwrite issue. I think the other issue with methods is solved too. Although I checked the documentation on the methods many times, I wasn't aware of the lazy evaluation scheme. That's probably why the` drop()` and` select()` aren't immediately applied unless the dataset is copied or `run()` is applied.
