### ISSUE TITLE
CircleCI failing

### ISSUE THREAD

**Issue by robertjwilson** [pmlmodelling/nctoolkit#22]
CircleCI is failing. [See here.](https://app.circleci.com/pipelines/github/pmlmodelling/nctoolkit/184/workflows/e8a7d2e5-ed87-4bc8-beeb-909dd1f870dd/jobs/179)

This appears to be an internal issue with CircleCI. `ImportError: /opt/conda/envs/nctoolkit/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found` cannot be reproduced locally and GitHub actions is OK. So the circle ci .yaml probably needs tweake to force it to pick up the correct glibc

**Comment by r4ecology** [comment]
This is still failing. Linux testing has been switched to GitHub Actions.

**Comment by robertjwilson** [comment]
This has been resolved by removing a cartopy install, which for some reason was breaking the circleci build.
