### ISSUE TITLE
ValueError: This version of nctoolkit is not compatible with CDO versions 2.0.0 and above

### ISSUE THREAD

**Issue by hilorywilsmart** [pmlmodelling/nctoolkit#26]
**ValueError: This version of nctoolkit is not compatible with CDO versions 2.0.0 and above**
I installed nctoolkit in jupyter notebook using "pip install nctoolkit" and restart the kernel as suggested. I got the error message described below. I tried it again using spyder, the same error message still occured
```
import nctoolkit as nc
nctoolkit is using Climate Data Operators version 2.0.4
`---------------------------------------------------------------------------`
ValueError                                Traceback (most recent call last)
Input In [1], in <module>
----> 1 import nctoolkit as nc

File ~/anaconda3/envs/TUTORIAL/lib/python3.9/site-packages/nctoolkit/__init__.py:31, in <module>
     27 from nctoolkit.mp_adders import match_points
     29 session_info["cdo"] = cdo_version()
---> 31 validate_version()

File ~/anaconda3/envs/TUTORIAL/lib/python3.9/site-packages/nctoolkit/utils.py:106, in validate_version()
    102     print(
    103         "Please install CDO version 1.9.7 or above: https://code.mpimet.mpg.de/projects/cdo/ or https://anaconda.org/conda-forge/cdo"
    104     )
    105 if bad:
--> 106     raise ValueError(
    107         "This version of nctoolkit is not compatible with CDO versions 2.0.0 and above"
    108     )

ValueError: This version of nctoolkit is not compatible with CDO versions 2.0.0 and above
```
![image](https://user-images.githubusercontent.com/111122178/185745042-a153ab2c-2675-4bab-aa95-a8e2f2acc9a8.png)

**Expected behavior**
I expect "import nctoolkit as nc" not to report any error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 -  - Version: 22

**Comment by r4ecology** [comment]
Have you installed CDO? If not, instructions are given here https://nctoolkit.readthedocs.io/en/latest/installing.html

**Comment by hilorywilsmart** [comment]
Yes, I have it installed. I've a way around it. I applied one of your comments that says nctoolkit is now compatible with cdo version >= 2.0.5, so I removed the version 2.0.4 and install version 2.0.6 and it stops giving the error message

**Comment by r4ecology** [comment]
There were some bugs in early 2.0.x versions of CDO that broke some of nctoolkit, so I took the conservation decision to require users do install a different version
