### ISSUE TITLE
Unable to import nctoolkit in Spyder for Mac 

### ISSUE THREAD

**Issue by MatthewChinappa** [pmlmodelling/nctoolkit#28]
Hi,
Im Unable to import nctoolkit in Spyder for Mac. it gives me this error:

>>> import nctoolkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthew/opt/miniconda3/envs/env/lib/python3.10/site-packages/nctoolkit/__init__.py", line 54, in <module>
    if valid(cdo_version) is False:
  File "/Users/matthew/opt/miniconda3/envs/env/lib/python3.10/site-packages/nctoolkit/__init__.py", line 26, in valid
    where = [m.start() for m in re.finditer(sub, string)][n - 1]
IndexError: list index out of range

**Comment by robertjwilson** [comment]
What version of nctoolkit is installed @MatthewChinappa ? Potentially this is out of date. I have had some issues making it available for all Python versions on conda, so this could just be a versioning issue.

**Comment by MatthewChinappa** [comment]
> What version of nctoolkit is installed @MatthewChinappa ? Potentially this is an old one that features a bug. I have had some issues making it available for all Python versions on conda, so this could just be a versioning issue.
> 
> In fact, based on the error this is definitely not a recent version. It actually looks like it's going back to version 0.2x

I downloaded the most recent version from the website, unless you can point me to the latest version and I can give it a try

**Comment by robertjwilson** [comment]
How have you installed it @MatthewChinappa? I'm not sure what you mean by download. Was this downloaded via github?

pip install should install the most recent version, but conda might go back a bit. And I'm not entirely sure what will be installed on osx for python 3.10, as there isn't currently a 3.10 specific osx version there. On osx it's probably better to install via pip, as there are ongoing problems with conda forge building nctoolkit for all python versions on osx.

**Comment by MatthewChinappa** [comment]
by download I meant both I have pip installed and conda forged. I still get the same error

**Comment by robertjwilson** [comment]
Can you check the version @MatthewChinappa?

This should tell you:

    from importlib.metadata import version
    version('nctoolkit')

Without knowing that it's hard for me to investigate whether this is a bug in the current or previous release. Though based on the error this is an old(ish) release.

**Comment by robertjwilson** [comment]
Does this problem still exist @MatthewChinappa? If not, I will close the issue.

**Comment by MatthewChinappa** [comment]
Hi @robertjwilson,thank you, the problem no longer exists

**Comment by robertjwilson** [comment]
Thanks @MatthewChinappa. Closing the issue now.
