### ISSUE TITLE
Permanently set temp dir?

### ISSUE THREAD

**Issue by christensen5** [pmlmodelling/nctoolkit#3]
I am using nctoolkit to create subsets of netcdf files containing high-resolution global ocean data. Since the files are large, and my Ubuntu root dir is relatively small, I choose to set the nctoolkit temp dir to a folder on my SSD whenever I do this. It would be very helpful if there were a config file where I could set this temp dir permanently, rather than having to run `nctoolkit.options(temp_dir = "...")` every time.

My apologies if this is already possible and I just haven't worked out how to do it; I looked in the site-packages/nctoolkit directory of my python installation for a config file but none exists, and the readthedocs for the nctoolkit only contains instructions for how to change the temp dir during an open python session.

**Comment by r4ecology** [comment]
Hi

Right now there isn't a way to do this. The present method was only added a month or so ago. 

I think I can solve this easily using the data_files  option in distutils. I'll have a go at this over the next couple of days. 

There are other options such as lazy that could probably benefit from global configuration.

**Comment by r4ecology** [comment]
Hi

I have now updated the development code to make this possible.

It is now possible to globally set the arguments sent to nc.options using a .nctoolkitrc or nctoolkitrc file.

An example of the file format is here [here](https://github.com/pmlmodelling/nctoolkit/blob/master/tests/.nctoolkitrc). That is one I am using for testing. The required layout of the file should be obvious, I hope.

The file should be placed either in your working directory or your home directory. When nctoolkit is imported it will look for a .nctoolkitrc file in your working directory and then in your home directory. It will then pull the global settings in from the first one it finds.

Let me know if this covers your use cases. I'll update the package website once I create a new pypi release, which should be early February.

**Comment by christensen5** [comment]
Thank you very much for this feature. I'll test it ASAP. I just have two questions regarding the options in the rc file:

1) Assuming my CPU allows SMT/hyperthreading, can nctoolkit make use of individual threads or just physical cores? For example if I have a 6-core 12-thread CPU can I set "cores: 12" or only "cores: 6" in the rc file?

2) What do the "user:" and "password:" options refer to? Is this to authorise nctoolkit to access netCDF files which only certain users on the local machine have permissions for? If so I presume I can simply remove those options from the nc file if my netCDF files have access restrictions?

Thanks again, this is a really nice QoL feature to have added so promptly.

**Comment by r4ecology** [comment]
Thanks

user/password should be ignored for now, as they are for a new feature I'm testing. I shouldn't have included user/password in the last public release.

You should be able to set cores to 12 in the rc file. It will check the number of cores available to you (i.e. whatever the multiprocessing module says is available), and throw an error if you have too many. Though I find on my own 6-core 12-thread machine there is a very minor speed improvement above 4 or 5 cores. Limiting factors probably vary by machine mind you.

I've also just finished modifying the dev version so that you can write your own code to batch process multiple files in parallel. Existing releases aren't parallel-safe, except for the internal parallel processing of multi-file datasets. The package website will have examples of how to parallel process files once I release the new pypi version early in February.

**Comment by christensen5** [comment]
Great, thanks for clarifying. I can confirm that on my system (Ubuntu 20.04 LTS), setting an rc file in home sets the nctoolkit options to the values in that file upon importing nctoolkit, and that having an rc file in the present working directory will override the settings specified by the home rc file. Happy to close the issue at this point.

I don't currently need to leverage parallel processing of multiple files, but there is a chance this would be helpful in the near-ish future so I look forward to trying that out in February if so.

**Comment by r4ecology** [comment]
Excellent. I'll close the issue.

**Comment by r4ecology** [comment]
A new public release has just been made with this feature included @christensen5 .
