### ISSUE TITLE
pip install nctoolkit ERROR: Failed building wheel for cartopy, how to exclude it ?

### ISSUE THREAD

**Issue by denis-bz** [pmlmodelling/nctoolkit#48]
```
pip install --prefix site/nc nctoolkit
# run: 1 Mar 2023 12:13  in ~bz/py/pip  Denis-iMac  mac 10.15.7  python 3.9.13
...
     lib/cartopy/trace.cpp:767:10: fatal error: 'geos_c.h' file not found
      #include "geos_c.h"
      error: command '/usr/bin/clang' failed with exit code 1
 ```
Would you know who under `cdo ...` reuires cartopy ? Is there a way to exclude it, a la
https://stackoverflow.com/questions/67165092/optionally-exclude-some-dependencies-when-pip-installing 

(What I really want to do is read COSMO_REA6 windspeed timeseries like those under
https://opendata.dwd.de/climate_environment/REA/COSMO_REA6/converted/hourly/2D
Know anyone who's done that, and lived to tell the tale ?)
Thanks,
cheers
  -- denis

**Comment by robertjwilson** [comment]
Cartopy can be tricky to install. I don't use osx, so can't provide much specific advice. However, cartopy is only used in nctoolkit to create better looking plots, and you don't really need it.

I recommend installing nctoolkit without dependencies, and then just add them when you need them:

    pip install --no-dependencies nctoolkit
    pip install --no-dependencies ncplot
    pip install xarray
    pip install hvplot
    pip install dill

etc.

and ensure you have any system dependencies installed: https://nctoolkit.readthedocs.io/en/latest/installing.html

**Comment by denis-bz** [comment]
@robertjwilson, one at a time is impractical, a never-ending story.
What are the *minimal* dependencies -- could you show the tree
or better, a pip requirements.txt ?
(I suppose you'd say "just use conda"  but I really don't want to mix conda and pip trees.)

Fwiw https://www.wheelodex.org/projects shows
ncplot -> geoviews metpy
geoviews -> cartopy
metpy -> cartopy

**Comment by robertjwilson** [comment]
Just install these, but make sure there are no depencencies for nctoolkit and ncplot

https://github.com/pmlmodelling/nctoolkit/blob/master/requirements.txt

**Comment by robertjwilson** [comment]
Closing this because of lack of reply
