### ISSUE TITLE
Typo in documentation: `Speeding up multi-file processing` section  of the Ensembles page.

### ISSUE THREAD

**Issue by ledm** [pmlmodelling/nctoolkit#53]
There's a typo on the `Speeding up multi-file processing` section  of the Ensembles page: 

https://nctoolkit.readthedocs.io/en/latest/ensembles.html#speeding-up-multi-file-processing

```
nc.options(6)
```

should be:

```
nc.options(cores = 6)
```

**Comment by robertjwilson** [comment]
Good spot @ledm . [This](https://github.com/pmlmodelling/nctoolkit/commit/85cf15dd1313008dc27f3b220e8f9eadd89537bb) fixes it.
