### ISSUE TITLE
[JOSS] Add guidelines on how to contribute

### ISSUE THREAD

**Issue by platipodium** [pmlmodelling/nctoolkit#62]
Especially clarify

- the desired workflow for contributions
- the legal ramifications (Contributor license agreement) for contributions

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
Can you clarify if this refers to the paper, website or Github @platipodium?

**Comment by platipodium** [comment]
Sure, I guess it should be in both the paper in your "Statement of need" section, as well as on the web site.

**Comment by platipodium** [comment]
I see you did this.  So closed as completed. Thanks!
