### ISSUE TITLE
[JOSS] Add guideline for how to seek support / report problems

### ISSUE THREAD

**Issue by platipodium** [pmlmodelling/nctoolkit#63]
Especially clarify

- the desired communication path (email,  issue, wiki, forum ...)  for support
- the desired communication path (email,  issue, wiki, forum ...)  for  problems

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
Can you clarify if this refers to the paper, website or Github @platipodium?

**Comment by platipodium** [comment]
I think most users would not expect this information in the JOSS paper nor on the website (but possibly on readthedocs), clearly this should be resolved on the GitHub repo. 

I would search for such information  at
- the end of the ReadMe
- in a file called `Reporting.md`,  `Bugs.md`, `Support.md`, `Contributing.md` or the like in the main directory (best referenced to from `ReadMe`

But JOSS requirement is only that such information is available (and, I guess, findable)

**Comment by robertjwilson** [comment]
This info has now been added to the end of the README: https://github.com/pmlmodelling/nctoolkit

**Comment by platipodium** [comment]
Thanks.  Closed as completed
