### ISSUE TITLE
[JOSS] ambiguous data path in paper example

### ISSUE THREAD

**Issue by platipodium** [pmlmodelling/nctoolkit#65]
In the JOSS paper, you write

```
ds_clim = nc.open_data("sst.mon.mean.nc")
ds_present = nc.open_data("data/sst.mon.mean.nc")
```

This is misleading.  Are both datasets the same file?  Why in different folders?

See https://github.com/openjournals/joss-reviews/issues/5494

**Comment by platipodium** [comment]
... and while you're at it, the title command exceeds the line length, so you could introduce a line break :=)

**Comment by robertjwilson** [comment]
Path is now fixed along with line break.
