### ISSUE TITLE
[JOSS] Compare nctoolkit with existing tools and find a better example

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#68]
Hi there,

Nice package! I didn't have the time to review it yet, but I glanced through the documentation and the paper.

My first comment is actually a question that I think you should address both in the paper and in the documentation: How does this tool compare to other existing packages?

I don't find the example in the paper particularly convincing, so my suggestion is to find a better one that really highlights the strengths of `nctoolkit`.

`xarray` is my go-to library for this kind of processing, and the example in the paper looks quite similar (although the plot is not publication ready, so that's definitely a strength of nctoolkit):
```python
import fsspec
import cartopy.crs as ccrs
import xarray as xr

url = "https://downloads.psl.noaa.gov/Datasets/COBE/sst.mon.mean.nc"
with fsspec.open(f"simplecache::{url}", simplecache={"same_names": True}) as f:
    ds = xr.open_mfdataset(f.name)

ds_clim = ds.sel(time=slice("1900", "1919")).mean("time")
ds_pres = ds.sel(time=slice("2000", "2019")).mean("time")
ds_anom = ds_pres - ds_clim

ds_anom["sst"].plot(
    transform=ccrs.PlateCarree(), subplot_kws={"projection": ccrs.Robinson()}
)
```
![image](https://github.com/pmlmodelling/nctoolkit/assets/22245117/7b5dd23e-0736-46dd-bbe5-a3c769400bcc)

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by malmans2** [comment]
Another comment about the example shown in the paper, looks like you already have a method to read/download from an url.
So I'd suggest to use that in the example rather than using a local path to a pre-downloaded file.

**Comment by platipodium** [comment]
related to #58

**Comment by robertjwilson** [comment]
I've created a new example, which shows how to calculate changes in surface temperature from global climate models. This is something that you can just do in nctoolkit, whereas with other tools like xarray or iris, you normally have to google it. The example also uses the `annual_anomaly` method to show that it's easy to calculate changes against baselines.

https://github.com/pmlmodelling/nctoolkit/actions/runs/5654799069


Word limit of 1000 words is tight, so I've added a short list of netCDF packages in the ecosystem. 

"The nctoolkit package sits within a Python ecosystem of packages such as xarray and iris, which provide data models and analysis software for netCDF, netCDF4 which provides low level access to netCDF data, and specialist software such as xesmf for processes such as regridding. In contrast to other netCDF libraries, the use of CDO as a back-end allows nctoolkit users to carry out operations, such as spatial averages, without having to specify the specific names of coordinates, such as longitude, latitude and time, which enables code written for one dataset to be easily applied to another."

The key point is that nctoolkit is somewhat more format-agnostic than xarray or iris. Illustrated with the example of `spatial_mean`. In both [xarray](https://docs.xarray.dev/en/stable/examples/area_weighted_temperature.html) and [iris](https://scitools-iris.readthedocs.io/en/latest/generated/gallery/meteorology/plot_COP_1d.html) this requires a few lines of code. 

The same is true for temporal averaging in nctoolkit using `tmean` for all types, whereas in xarray it's a slightly confusing combination of `mean`, `groupby` and `resample` to do things. But I'll just stick with spatial average in the paper.

**Comment by malmans2** [comment]
Looks good and I think it makes much more clear the scope of `nctoolkit`.
Could you please add instructions/code to download the example data?

**Comment by malmans2** [comment]
Thanks!
