### ISSUE TITLE
hi. 

### ISSUE THREAD

**Issue by Jashaviti** [pmlmodelling/nctoolkit#7]
Hi, 
I was following the manual to use sqrt. it seems that this attribute is no longer available in the current version? while I have ended up manually calculating it, it might be nice to have ( in a future version) the function built directly into nctoolkit.  perhaps even as far as some basic statistical tests? Again, I am very appreciative of how wonderful the toolkit is.

**Comment by r4ecology** [comment]
Thanks

Not officially working right now, so I can't look into this properly until next week.

In short, `sqrt` has never been a method. But you can calculate square roots using `assign` and using `sqrt` within it.

However it is not difficult for me to add in a `sqrt` method. I should possibly add methods for a selection of the CDO methods that are listed on page 86 here: https://code.mpimet.mpg.de/projects/cdo/embedded/cdo.pdf. It would take a couple of hours max to add those methods and they are likely useful, so I will try to do it over the next couple of weeks.

However, if you wanted to do this now you should be able to do this:

    ds.cdo_command('sqrt')

**Comment by r4ecology** [comment]
I have now added a `sqrt` method. Usage is straight forward:

    ds.sqrt()

This is part of the v0.3.7 release that I've just push to pypi. It will be on conda-forge in a few hours.

There are also `abs``, ``power``, ``square``,  ``exp``, ``log`` and ``log10`` methods in the new release.
