### ISSUE TITLE
[JOSS] Speed up tests and address warnings

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#70]
I was looking at the GH actions, and I noticed it takes +1h to run the tests.
It would be nice to speed up both the setup (+10min) and testing steps (+30min), especially if you encourage external contributions.

For the setup step, I recommend to use this action: https://github.com/mamba-org/setup-micromamba
Micromamba is generally much faster, and the action provides an option to activate the environment cache.

Also, if you didn't notice it, there are a few warnings raised both by `pytest` and GitHub actions.
For example, see: https://github.com/pmlmodelling/nctoolkit/actions/runs/5198818724
I suggest to solve the GitHub actions warnings, and [assert](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html#warns) or solve pytest warnings. 

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
Thanks for the suggestion @malmans2. Figuring out if tests can be switched to mamba. I've managed to get that working this afternoon, after much tweaking with the yml. It knocked about 15 minutes of the run time: https://github.com/pmlmodelling/nctoolkit/actions/runs/5202108978.

Overall the tests are too thorough, so I can probably get the overall run time below 10 minutes easily enough, now that installs aren't an issue.

**Comment by malmans2** [comment]
Nice!
This software could be useful to debug GH actions: https://github.com/nektos/act
I've never used it myself though, I just thought you might find it useful.
If you end up using it, let me know how it goes!

**Comment by malmans2** [comment]
I'll close this as the tests now take less than 10min.
Note that you still have a warning:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, codecov/codecov-action@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

You are not using the latest codecov version (you can use [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) to keep actions up to date).

**Comment by robertjwilson** [comment]
Thanks @malmans2. macOS tests are still running slow, because CDO is slower on macOS at least on GitHub's architecture. But I should maybe just switch those tests to daily builds.

I've raised an issue to get the dependabot issue fixed: https://github.com/pmlmodelling/nctoolkit/issues/85
