### ISSUE TITLE
[JOSS] Add version to the cheat sheet

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#72]
The cheat sheet is very helpful!
Is the cheatsheet in sync with the code?
Ideally, you need a GH action that generates it.
But if that's not feasible, I suggest to mention `nctoolkit` version in the cheat sheet.

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
It's in synch, but agreed, it needs a version number.

I've been thinking of rewriting it in html, so that it can go on the website. Once I do that it might be feasible to autogenerate, or at least a test on GH actions to ensure it's up to date.

**Comment by robertjwilson** [comment]
The version number is [now added](https://github.com/pmlmodelling/nctoolkit/blob/master/cheatsheet/nctoolkit_cheatsheet.pdf)

I have raised an issue to generate the cheatsheets using a similar approach to RStudio, who use Quarto which will pull in version numbers etc. https://github.com/pmlmodelling/nctoolkit/issues/75
