### ISSUE TITLE
[JOSS] Why is Windows not supported?

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#74]
Why is Windows not supported? Is it a nightmare to maintain?
I just want to make sure that you considered supporting it, I understand that it might be high effort/low reward.
So feel free to close if there's no point in supporting windows.

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
CDO does not have native Windows support: https://code.mpimet.mpg.de/projects/cdo/wiki/Win32. It can be installed using cygwin on Windows, but supporting this in nctoolkit would be pretty difficult/elaborate and not likely worth it as netCDF users primarily work on Linux.
