### ISSUE TITLE
[JOSS] Documentation notebooks

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#78]
Are the documentation notebooks executed by readthedocs?
If not, I suggest to do that and to store notebooks without any output (e.g., I often use [nbstripout with pre-commit](https://github.com/kynan/nbstripout#using-nbstripout-as-a-pre-commit-hook)).

If you need to show notebooks that need a long run time, I suggest to always print `nctoolkit` version at import.

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
The notebooks are currently run locally. Improving this is on my to-do list, but it's not a short piece of work so it's not high on the list. I'd probably need to rewrite a lot of them to use readthedocs as the files are a) downloaded and b) too large to store somewhere like Github.

I've closed the issue as it's out of scope for JOSS in my view, but I've raised this issue to ensure it's dealt with in future. https://github.com/pmlmodelling/nctoolkit/issues/79
