### ISSUE TITLE
[JOSS] Performance: Show that nctoolkit is fast

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#81]
**Fast** and **easy** analysis of netCDF data in Python.

The fact that `nctoolkit` is **easy** to use is well shown and explained throughout the documentation. 
Is there a section that explains and shows that it's also **fast**?

**Comment by robertjwilson** [comment]
Benchmarking is a tricky one. My experience of this is that it's hard to tell if there is any real difference between nctoolkit and xarray for example. 

I've added a notebook I've run on Linux, doing benchmarks of temporal averages and spatial means. Typically, run time is within about 50% of each other. Though xarray tends to be faster for small files, where speed is important.

https://github.com/pmlmodelling/nctoolkit/blob/master/benchmarks/benchmark_nctoolkit_versus_xarray.ipynb

Something like this could be added to the website, but it's hard to do these things without people getting suspicious you are cherry picking and not believing you in the first place.

**Comment by malmans2** [comment]
I think some sort of benchmark should be added to the website because both the documentation and GitHub About say: [nctoolkit: Fast and easy analysis of netCDF data in Python](https://nctoolkit.readthedocs.io/en/latest/index.html#nctoolkit-fast-and-easy-analysis-of-netcdf-data-in-python).
Alternatively, you could just use the same title used for the paper: 
> `nctoolkit: A Python package for netCDF analysis and post-processing`


About the notebook:

IMO the benchmark notebook is not as clear as the other notebooks.
Here are a few suggestions:
1. Keep it as simple as possible (e.g., can you use [tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) instead of writing your own code?)
2. Separate xarray and nctoolkit code in dedicated functions
3. Make the results more robust. E.g., if the benchmark is done through jupyter, you could do this: `timing = %timeit func(...)`

Here is an example:
```python
def compare(xr_func, nc_func, check=True):
    results = {}
    for bin in bins:
        # create dataset for benchmark
        with tempfile.NamedTemporaryFile(suffix=".nc") as tmpfile:
            # write dataset for benchmark
            if check:
                xr.testing.assert_allclose(xr_func(tmpfile.name), nc_func(tmpfile.name))
            xr_timing = %timeit xr_func(tmpfile.name)
            nc_timing = %timeit nc_func(tmpfile.name)
            results[bin] = {"xr": xr_timing, "nc": nc_timing}
    return results


def xr_spatial_mean(path):
    ds = xr.open_dataset(path)
    ...
    return ds


def nc_spatial_mean(path):
    ds = nc.open_data(ff_orig)
    ...
    return ds.to_xarray()


spatial_mean_timings = compare(xr_spatial_mean, nc_spatial_mean)
```

One final comment, if dask in not going to be used in the benchmark, I would explicitly mention it as it's an important feature of xarray.

**Comment by robertjwilson** [comment]
I've changed the github page title to match the paper title. https://github.com/pmlmodelling/nctoolkit

Originally, the word "fast" was referring to time spent writing code, not really computation. But I'm happy to just replace the title.

In my experience not many people pay attention to or even look at benchmarks. So there is probably little reward to adding it to the website. Certainly xarray and most packages don't have anything.

**Comment by malmans2** [comment]
OK, sorry if I wasn't clear.
> The authors define the software as fast and easy to use. I don't know exactly what fast means in this context (maybe compared to other libraries?), and how to confirm it. The documentation is missing a section that shows that the software is fast.

My point was that it's not clear what fast means in this context, it could mean something like [ruff](https://beta.ruff.rs/docs/) or [this JOSS paper](https://joss.theoj.org/papers/10.21105/joss.03675), which would require a benchmark.

IMO the title you used in the paper is more clear.
If still see the old title both in the About section and in the [latest documentation](https://nctoolkit.readthedocs.io/en/latest/): 
![Screenshot 2023-08-03 at 12 36 56](https://github.com/pmlmodelling/nctoolkit/assets/22245117/11aa16fa-44d1-4615-8ac0-a3b5ca7bcc27)

**Comment by robertjwilson** [comment]
Just hadn't got round to pushing those changes. All titles should be changed now. pypi etc. should change once a new release is available.

https://nctoolkit.readthedocs.io/en/latest/

**Comment by malmans2** [comment]
Thanks.
