### ISSUE TITLE
Caching for downloaded files

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#83]
I think it would be nice to implement caching for downloaded files (e.g., `open_url` and `open_thredds`).
`pooch` might be a good library for that: https://www.fatiando.org/pooch/

**Comment by robertjwilson** [comment]
That's a good suggestion @malmans2. I've just raised an issue to implement it https://github.com/pmlmodelling/nctoolkit/issues/89.

This can maybe be solved for `open_url` by adding a dictionary that tracks which urls were downloaded and what the temp location is. Probably a simple enough bit of book-keeeping.
