### ISSUE TITLE
Unable to parse dataset contents. Consider running checks on dataset

### ISSUE THREAD

**Issue by Gilaverbuch** [pmlmodelling/nctoolkit#88]
I've been trying to run one of the examples but it cannot read the .nc files. The file is fine because xarray can read it. Any advice here?

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~/opt/miniconda3/envs/pysst/lib/python3.11/site-packages/nctoolkit/api.py:1433, in DataSet.show_contents(self, n)
   1432 while True:
-> 1433     if out_inc[i]:
   1434         break

IndexError: list index out of range

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[21], line 1
----> 1 ds = nc.open_data("sst.mon.mean.nc")
      2 ds.subset(year = 2000)
      3 ds.plot()

File ~/opt/miniconda3/envs/pysst/lib/python3.11/site-packages/nctoolkit/api.py:836, in open_data(x, checks, **kwargs)
    833 d._thredds = thredds
    835 if (len(d) == 1) and checks and (thredds is False):
--> 836     d_contents = d.contents.reset_index(drop=True)
    837     try:
    838         d_sub = d_contents.query("fill_value == 0.0").reset_index(drop=True)

File ~/opt/miniconda3/envs/pysst/lib/python3.11/site-packages/nctoolkit/api.py:1613, in DataSet.contents(self)
   1606 @property
   1607 def contents(self):
   1608     """
   1609     Detailed list of variables contained in a dataset.
   1610     This will only display the variables in the first file of an ensemble.
   1611     """
-> 1613     return self.show_contents()

File ~/opt/miniconda3/envs/pysst/lib/python3.11/site-packages/nctoolkit/api.py:1602, in DataSet.show_contents(self, n)
   1600         return pd.concat(list_contents).set_index("file")
   1601 except:
-> 1602     raise ValueError(
   1603         "Unable to parse dataset contents. Consider running checks on dataset"
   1604     )

ValueError: Unable to parse dataset contents. Consider running checks on dataset

`

**Comment by robertjwilson** [comment]
Have you checked that CDO is available in your environment? That sounds like nctoolkit is not picking it up.

**Comment by Gilaverbuch** [comment]
Thanks. You are right. I had it installed but it didn't recognize it. It's working now

**Comment by robertjwilson** [comment]
Thanks. Closing now.
